# Wrangling PANSTEATITIS study ST001052
---

This notebook carries out the wrangling process for the [LIVER study ST001052 lipidomics data](https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST001052&StudyType=MS&ResultType=1) [1].

## Libraries

In [1]:
using Pkg 

In [2]:
Pkg.activate(joinpath(@__DIR__, "..", ".."))

  Activating project at `~/git/gregfa/metabolomics/mlm-metabolomics-supplement/PANSTEATITISstudy`


In [60]:
Pkg.instantiate()

In [4]:
# To use RCall for the first time, one needs to 
# the location of the R home directory.
firstTimeRCall = false
if firstTimeRCall
    using Pkg
    io = IOBuffer()
    versioninfo(io)
    if occursin("Windows", String(take!(io)))
        ENV["R_HOME"] = "C:/PROGRA~1/R/R-43~1.1" # from R.home() in R
    else 
        ENV["R_HOME"] = "/usr/lib/R"

    end
    Pkg.build("RCall")
end      

In [5]:
using DataFrames, CSV
using FreqTables #, CategoricalArrays
using StatsBase
using RCall# Conda, PyCall
using MetabolomicsWorkbenchAPI

[ Info: Precompiling RCall [6f49c342-dc21-5d91-9882-a32aef131414] (cache misses: incompatible header (6))


## Ext. Functions

In [6]:
include(joinpath(@__DIR__,"..","..","src","wrangling_utils.jl" ));
include(joinpath(@__DIR__,"..","..","src","demog.jl" ));

## Load data ST001052

In [7]:
ST  = "ST001052";

## Extract clinical covariates

Use the Julia's API to get the samples data from the [metabolomics workbench](https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST001052).

In [8]:
# get clinical covariates
dfIndividuals =  fetch_samples(ST);
print_df_size(dfIndividuals)

The dataframe contains 53 rows and 17 columns


List of the covariate names: 

In [9]:
names(dfIndividuals)

17-element Vector{String}:
 "Sample ID"
 "Group"
 "Gender"
 "Date Captured"
 "Annuli"
 "Age"
 "WEIGHT (KG)"
 "LENGTH (CM)"
 "TG (CM)"
 "VET SCORE (Adipose)"
 "TOTAL PROTEIN (g/100mL)"
 "PCV Color"
 "PCV"
 "Histology Adipose"
 "Histology Liver"
 "Histology Swim Bladder"
 "NECROPSY NOTES:"

In [10]:
println("From the study description, $(ST) has $(fetch_total_subjects(ST)) subjects.")

From the study description, ST001052 has 51 subjects.


The clinical covariates dataframe contains 2 extra rows. We need to indicate what values corresponds to the `missing` data. In our case, all "-" will be replaced by `missing`.    

In [11]:
# assign missing value to "-"
dfIndividuals = ifelse.(dfIndividuals .== "-", missing, dfIndividuals);

Check number of missing per columns.

In [12]:
print_variables_missing(dfIndividuals)

Group contains 2 missing values.
Gender contains 2 missing values.
Date Captured contains 1 missing values.
Annuli contains 2 missing values.
Age contains 2 missing values.
WEIGHT (KG) contains 2 missing values.
LENGTH (CM) contains 2 missing values.
TG (CM) contains 2 missing values.
VET SCORE (Adipose) contains 16 missing values.
TOTAL PROTEIN (g/100mL) contains 3 missing values.
PCV Color contains 3 missing values.
PCV contains 3 missing values.
Histology Adipose contains 9 missing values.
Histology Liver contains 2 missing values.
Histology Swim Bladder contains 7 missing values.
NECROPSY NOTES: contains 14 missing values.


### Clinical dictionary

In [13]:
fileClinicalDict = joinpath(@__DIR__,"..","..","data","processed", "ClinicalDataDictionary.csv");
open(fileClinicalDict,"w") do io
   println(io,
        "Variable name, Variable description\n",
        "Gender,Sex\n",
        "Age, Years\n",
        "Weight (KG), Kilogram\n",
        "Length (CM), Centimeter\n",
        "Annuli,Number of opaque zones on fish scales\n",
        # "TG (CM),???\n",
        "VET SCORE,Veterinarian score where vet score < 1 indicates healthy tilapia and  vet score ≥ 1 indicates pansteatitis-affected tilapia.\n" ,
        "PCV Color,Pigmentation visually observed\n",
        "PCV,Pigmentation concentration volume\n",
        "Histology Adipose,Histological examination score of the adipose tissue\n",
        "Histology Liver,Histological examination score of the liver tissue\n",
        "Histology Swim Bladder,Histological examination score of the swim bladder tissue"
    )
end

### Independent variables

Select variables of interest:

In [14]:
select!(dfIndividuals, Symbol.(["Sample ID",
                                "Group",
                                "Gender",
                                "Annuli",
                                "Age",
                                "WEIGHT (KG)",
                                "LENGTH (CM)",
                                "Histology Adipose",
                                # "Histology Liver",
                                # "Histology Swim Bladder",
]));

Rename variables if needed:

In [15]:
rename!(dfIndividuals, Dict(
        :Group => "Status",
        :Gender => "Sex",
        Symbol("Sample ID") => "SampleID",
        Symbol("WEIGHT (KG)") => "Weight",
        Symbol("LENGTH (CM)") => "Length",
        Symbol("Histology Adipose") => "Histological_Score",
        # Symbol("Histology Liver") => "Histology_Liver",
        # Symbol("Histology Swim Bladder") => "Histology_Swim_Bladder",
));

#### Extract histology score   

The histology score spans between 0 and 5. Let write the histology dictionnary:   

In [16]:
fileHystologyDict = joinpath(@__DIR__,"..","..","data","processed", "HistologyDictionary.csv");
open(fileHystologyDict,"w") do io
   println(io,
        "Score, Histological Score Progression\n",
        "0, no signs\n",
        "1, minimal\n",
        "2, mild/few\n",
        "3, moderate",
        "4, moderate/severe\n",
        "5, severe\n",
    )
end

Create a function to extract each score:

In [17]:
function xtrcHistScore(vecHist) 
    idxnotmissing = findall(.!(ismissing.(vecHist)));
    vScore = Vector{Union{Missing, Int}}(undef, length(vecHist));
    for i in idxnotmissing
        if isdigit(vecHist[i][1])
           vScore[i] = parse(Int, vecHist[i][1]) 
        end
    end
    
    return vScore
end;

Replace original histology text by extracted score:

In [18]:
dfIndividuals.Histological_Score .= xtrcHistScore(dfIndividuals.Histological_Score);
# dfIndividuals.Histology_Liver .= xtrcHistScore(dfIndividuals.Histology_Liver);
# dfIndividuals.Histology_Swim_Bladder .= xtrcHistScore(dfIndividuals.Histology_Swim_Bladder);

Filter incomplete cases:

In [19]:
# filter complete cases
idxComplete = findall(completecases(dfIndividuals))
dfIndividuals = dfIndividuals[idxComplete, :]

# add a prefix to the ID samples
dfIndividuals.SampleID = "ID_".*string.(dfIndividuals.SampleID);

first(dfIndividuals, 5)

5×8 DataFrame
 Row │ SampleID  Status   Sex      Annuli   Age      Weight   Length   Histolo ⋯
     │ String    String?  String?  String?  String?  String?  String?  Int64?  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ ID_8358   FD       F        7        8        1.3      40               ⋯
   2 │ ID_8363   FD       F        12       13       1.5      40
   3 │ ID_8370   FD       F        10       11       1.4      40.5
   4 │ ID_8371   FD       F        11       12       1.4      41
   5 │ ID_8373   FD       F        12       13       1.9      43.5             ⋯
                                                                1 column omitted

Insert a `GroupStatus` variable. The `Group` variable includes the diseases status and gender:

In [20]:
unique(dfIndividuals.Status)

4-element Vector{Union{Missing, String}}:
 "FD"
 "FH"
 "MD"
 "MH"

Let redefine the `Status` variable:

In [21]:
# insertcols!(dfIndividuals, 3, :GroupStatus => occursin.("D", dfIndividuals.Group));
idxDiseased = findall(occursin.("D", dfIndividuals.Status)) ;
idxHealthy = findall(occursin.("H", dfIndividuals.Status));

dfIndividuals.Status[idxDiseased] .= "Diseased";
dfIndividuals.Status[idxHealthy] .= "Healthy";

idxMale = findall(occursin.("M", dfIndividuals.Sex)) ;
idxFemale = findall(occursin.("F", dfIndividuals.Sex));

dfIndividuals.Sex[idxMale] .= "Male";
dfIndividuals.Sex[idxFemale] .= "Female";

In [22]:
first(dfIndividuals, 5)

5×8 DataFrame
 Row │ SampleID  Status    Sex      Annuli   Age      Weight   Length   Histol ⋯
     │ String    String?   String?  String?  String?  String?  String?  Int64? ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ ID_8358   Diseased  Female   7        8        1.3      40              ⋯
   2 │ ID_8363   Diseased  Female   12       13       1.5      40
   3 │ ID_8370   Diseased  Female   10       11       1.4      40.5
   4 │ ID_8371   Diseased  Female   11       12       1.4      41
   5 │ ID_8373   Diseased  Female   12       13       1.9      43.5            ⋯
                                                                1 column omitted

#### Save processed individuals dataset:

In [23]:
fileIndividuals = joinpath(@__DIR__,"..","..","data","processed","ST001052_ClinicalCovariates.csv");
dfIndividuals |> CSV.write(fileIndividuals);

### Demography

In [24]:
dfDemog = getDemographicST001052()

11×2 DataFrame
 Row │ Clinical Features   Count/ mean(SD) 
     │ Any                 Any             
─────┼─────────────────────────────────────
   1 │ Status
   2 │ Diseased            30
   3 │ Healthy             14
   4 │ Sex
   5 │ Female              20
   6 │ Male                24
   7 │ Annuli              8.3(2.66)
   8 │ Age                 9.3(2.66)
   9 │ WEIGHT (KG)         1.67(0.31)
  10 │ LENGTH (CM)         42.35(2.31)
  11 │ Histological Score  2.45(1.41)

In [25]:
fileDemog = joinpath(@__DIR__,"..","..","data","processed","Demog.csv");
dfDemog |> CSV.write(fileDemog);

## Extract Metabolite references

In [26]:
# get clinical covariates
dfRef =  fetch_metabolites(ST);
print_df_size(dfRef)

The dataframe contains 590 rows and 10 columns


List the name of available properties:

In [27]:
names(dfRef)

10-element Vector{String}:
 "Metabolite"
 "quantified m/z"
 "rtimes"
 "ID_Ranked (LipidMatch OR LipidSearch annotation/rank)"
 "Class_At_Max_Intensity"
 "Adduct_At_Max_Intensity"
 "(LipidMatch Normalizer output)"
 "IS_Species"
 "IS_Adduct"
 "Neg & Pos Confirmed"

In [28]:
first(dfRef, 5)

5×10 DataFrame
 Row │ Metabolite  quantified m/z  rtimes       ID_Ranked (LipidMatch OR Lipid ⋯
     │ String      String          String       String                         ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ CE(18:1)    668.634144      15.04984231  1_CE(18:1)+NH4                 ⋯
   2 │ CE(18:2)    666.6186284     14.54040077  1_CE(18:2)+NH4
   3 │ CE(18:3)    664.6024729     14.00371744  1_CE(18:3)+NH4
   4 │ CE(18:4)    662.5874291     13.40464795  1_CE(18:4)+NH4
   5 │ CE(20:1)    696.6651802     15.52861207  1_CE(20:1)+NH4                 ⋯
                                                               7 columns omitted

Create a metabolite ID and keep only name and ID:

In [29]:
dfRef.MetaboliteID = "MT" .* string.(10000 .+ collect(1:size(dfRef, 1)));
select!(dfRef, [:Metabolite, :MetaboliteID]);

### Get Classification information

To get the classifciation information, we use the package `MetabolomicsWorkbenchAPI.jl`.

In [30]:
dfClassification = fetch_properties(dfRef.Metabolite);
# insertcols!(dfClassification, 1, :metabolite_name => dfRef.metabolite_name);
first(dfClassification, 3)

3×6 DataFrame
 Row │ exactmass  formula   main_class     refmet_name  sub_class     super_cl ⋯
     │ String?    String?   String?        String?      String?       String?  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 650.6002   C45H78O2  Sterol esters  CE 18:1      Chol. esters  Sterol L ⋯
   2 │ 648.5845   C45H76O2  Sterol esters  CE 18:2      Chol. esters  Sterol L
   3 │ 646.5689   C45H74O2  Sterol esters  CE 18:3      Chol. esters  Sterol L
                                                                1 column omitted

In [31]:
dfRef |> names

2-element Vector{String}:
 "Metabolite"
 "MetaboliteID"

In [32]:
dfClassification |> names

6-element Vector{String}:
 "exactmass"
 "formula"
 "main_class"
 "refmet_name"
 "sub_class"
 "super_class"

In [33]:
# replace "-" by missing
for c ∈ eachcol(dfClassification)
           replace!(c, "-" => missing)
end

In [34]:
idxmissing = findall(ismissing.(dfClassification.main_class))
dfRef.Metabolite[idxmissing]

99-element Vector{String}:
 "OxLPC(20:2(OO))"
 "OxLPC(20:2(OOO))"
 "OxLPC(20:3(OH))"
 "OxLPC(20:4(OH))"
 "OxLPC(22:2(OO))"
 "OxLPC(22:2(OOO))"
 "OxLPC(22:3(OH))"
 "OxLPC(22:6(OOOO))"
 "OxPC(16:0_20:3(OH))"
 "OxPC(16:0_22:3(OH))"
 "OxPC(16:0_22:6(OO))"
 "OxPC(16:0_22:6(OOOO))"
 "OxPC(18:0_22:3(OH))"
 ⋮
 "plasmanyl-TG(O-20:1_16:0_18:1)"
 "plasmenyl-TG(P-20:1_15:0_16:0)"
 "plasmenyl-TG(P-20:1_16:0_18:0)"
 "plasmenyl-TG(P-20:1_16:1_18:1)"
 "PMe(16:0/18:1)"
 "TG(18:2+3O/16:0/17:0)"
 "TG(18:2+3O/17:0/22:5)"
 "TG(18:2+O/20:4/22:6)"
 "TG(18:3+3O/20:0/20:0)"
 "TG(22:5+O/22:4/22:6)"
 "TG(22:6+3O/18:1/19:0)"
 "ZyE(22:5)"

In [35]:
size(dfRef)

(590, 2)

To be able to use all the lipid, especially the Triglycerides, we need to adjust the name in a more standardized way to be able to extract their properties information.  
- The *Ox-* prefix mean oxidized, such as in *OxTG(16:0_20:5_20:3(OH))*. The *OH* indicates that it is a [TG hydroperoxide](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6550225/) [2].   
- The *P-* and the *O-* indicate respectively if the lipid is a plasmalogen or a plasmanyl, such as *plasmanyl-TG(O-20:0_18:0_18:4)* and *plasmenyl-TG(P-20:1_15:0_16:0)*[3].
- The non-oxidized lipids that contains Oxygen are described in [4].


In [36]:
dfRefOriginal = copy(dfRef);

In [37]:
dfRef = copy(dfRefOriginal);

In [38]:
dfRef.StandardizedName = copy(dfRef.Metabolite);

In [39]:
function standardizename(df::DataFrame, colname::String, matchstring)
    if !([colname] ⊆ names(df))
        df[:, colname] = repeat([false], size(dfRef, 1));
    end
    idx = findall(occursin.(matchstring, dfRef.Metabolite));
    df[idx, colname] .= true;
    # standardize name 
    df.StandardizedName[idx] .= replace.(dfRef.StandardizedName[idx], matchstring=>""); 
    return df
end

standardizename (generic function with 1 method)

In [40]:
newcolname = ["Oxidized", "OH", "O", "O₂", "O₃", "O₄", "Plasmanyl", "Plasmalogen",
              "O₂", "O₃", "Plasmanyl", "Plasmalogen", "CHO", "Ke", "O" ] 
rmvstring = ["Ox", "(OH)", "+O", "(OO)", "(OOO)", "(OOOO)", "O-", "P-",
             "+OO", "+3O", r"(?i)plasmanyl-", r"(?i)plasmenyl-", "(CHO)", "(Ke)", "O" ]
for i in 1:length(newcolname)
    dfRef = standardizename(dfRef, newcolname[i], rmvstring[i]);
end    

In [41]:
dfRef

590×13 DataFrame
 Row │ Metabolite             MetaboliteID  StandardizedName    Oxidized  OH   ⋯
     │ String                 String        String              Bool      Bool ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ CE(18:1)               MT10001       CE(18:1)               false  fals ⋯
   2 │ CE(18:2)               MT10002       CE(18:2)               false  fals
   3 │ CE(18:3)               MT10003       CE(18:3)               false  fals
   4 │ CE(18:4)               MT10004       CE(18:4)               false  fals
   5 │ CE(20:1)               MT10005       CE(20:1)               false  fals ⋯
   6 │ CE(20:2)               MT10006       CE(20:2)               false  fals
   7 │ CE(20:4)               MT10007       CE(20:4)               false  fals
   8 │ CE(20:5)               MT10008       CE(20:5)               false  fals
   9 │ CE(22:3)               MT10009       CE(22:3)               false  fals ⋯
  10 │ CE(22:4)               MT10010       CE(22:4)               false  fals
  11 │ CE(22:5)               MT10011       CE(22:5)               false  fals
  ⋮  │           ⋮                 ⋮                ⋮              ⋮        ⋮  ⋱
 581 │ TG(22:6/14:3/22:6)     MT10581       TG(22:6/14:3/22:6)     false  fals
 582 │ TG(22:6_22:6_22:6)     MT10582       TG(22:6_22:6_22:6)     false  fals ⋯
 583 │ TG(22:6_22:6_24:1)     MT10583       TG(22:6_22:6_24:1)     false  fals
 584 │ TG(22:6+3O/18:1/19:0)  MT10584       TG(22:6/18:1/19:0)     false  fals
 585 │ TG(24:2/22:6/22:6)     MT10585       TG(24:2/22:6/22:6)     false  fals
 586 │ TG(25:0/16:0/22:6)     MT10586       TG(25:0/16:0/22:6)     false  fals ⋯
 587 │ TG(26:1/16:0/22:6)     MT10587       TG(26:1/16:0/22:6)     false  fals
 588 │ TG(26:1/22:6/22:6)     MT10588       TG(26:1/22:6/22:6)     false  fals
 589 │ TG(28:1/16:0/22:6)     MT10589       TG(28:1/16:0/22:6)     false  fals
 590 │ ZyE(22:5)              MT10590       ZyE(22:5)              false  fals ⋯
                                                  9 columns and 569 rows omitted

In [42]:
dfClassification = fetch_properties(dfRef.StandardizedName);
insertcols!(dfClassification, 1, :Metabolite => dfRef.Metabolite);
first(dfClassification, 3)

3×7 DataFrame
 Row │ Metabolite  exactmass  formula   main_class     refmet_name  sub_class  ⋯
     │ String      String?    String?   String?        String?      String?    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ CE(18:1)    650.6002   C45H78O2  Sterol esters  CE 18:1      Chol. este ⋯
   2 │ CE(18:2)    648.5845   C45H76O2  Sterol esters  CE 18:2      Chol. este
   3 │ CE(18:3)    646.5689   C45H74O2  Sterol esters  CE 18:3      Chol. este
                                                               2 columns omitted

In [43]:
# replace "-" by missing
for c ∈ eachcol(dfClassification)
           replace!(c, "-" => missing)
end

In [44]:
idxmissing = findall(ismissing.(dfClassification.main_class))
dfRef.StandardizedName[idxmissing]

11-element Vector{String}:
 "PC(22:2_16:3)"
 "TG(16:0_22:6_22:3)"
 "TG(18:0_22:6_22:3)"
 "PC(20:1/16:0)"
 "PMe(16:0/18:1)"
 "TG(18:2/16:0/17:0)"
 "TG(18:2/17:0/22:5)"
 "TG(18:3/20:0/20:0)"
 "TG(22:5/22:4/22:6)"
 "TG(22:6/18:1/19:0)"
 "ZyE(22:5)"

At this stage, only *DMPE(16:0_22:6)* can be processed by [goslin](https://apps.lifs-tools.org/goslin/).   
We will filter *PMe(16:0/18:1)* (phosphatidylmethanol) [5] and *ZyE(22:5)*.


In [45]:
dfRef |> names

13-element Vector{String}:
 "Metabolite"
 "MetaboliteID"
 "StandardizedName"
 "Oxidized"
 "OH"
 "O"
 "O₂"
 "O₃"
 "O₄"
 "Plasmanyl"
 "Plasmalogen"
 "CHO"
 "Ke"

In [46]:
dfClassification |> names

7-element Vector{String}:
 "Metabolite"
 "exactmass"
 "formula"
 "main_class"
 "refmet_name"
 "sub_class"
 "super_class"

In [47]:
dfRef = leftjoin(dfRef, dfClassification, on = :Metabolite); size(dfRef)

(590, 19)

In [48]:
# filter
# deleteat!(dfRef, idxmissing[[2,3]]);
deleteat!(dfRef, idxmissing[[5,11]]);

In [52]:
dfRef.sub_class |> unique

14-element Vector{Union{Missing, String}}:
 "Chol. esters"
 "Cer"
 "DAG"
 "PE-NMe2"
 "LPC"
 "LPE"
 "PC"
 missing
 "TAG"
 "O-PC"
 "PE"
 "PI"
 "O-PS"
 "SM"

In [57]:
?skipmissing

search: skipmissing skipmissings dropmissing ismissing dropmissing! idxmissing



```
skipmissing(itr)
```

Return an iterator over the elements in `itr` skipping [`missing`](@ref) values. The returned object can be indexed using indices of `itr` if the latter is indexable. Indices corresponding to missing values are not valid: they are skipped by [`keys`](@ref) and [`eachindex`](@ref), and a `MissingException` is thrown when trying to use them.

Use [`collect`](@ref) to obtain an `Array` containing the non-`missing` values in `itr`. Note that even if `itr` is a multidimensional array, the result will always be a `Vector` since it is not possible to remove missings while preserving dimensions of the input.

See also [`coalesce`](@ref), [`ismissing`](@ref), [`something`](@ref).

# Examples

```jldoctest
julia> x = skipmissing([1, missing, 2])
skipmissing(Union{Missing, Int64}[1, missing, 2])

julia> sum(x)
3

julia> x[1]
1

julia> x[2]
ERROR: MissingException: the value at index (2,) is missing
[...]

julia> argmax(x)
3

julia> collect(keys(x))
2-element Vector{Int64}:
 1
 3

julia> collect(skipmissing([1, missing, 2]))
2-element Vector{Int64}:
 1
 2

julia> collect(skipmissing([1 missing; 2 missing]))
2-element Vector{Int64}:
 1
 2
```


In [58]:
findall(occursin.("PE-NMe2", skipmissing(dfRef.sub_class)))

1-element Vector{Int64}:
 29

In [59]:
skipmissing(dfRef.sub_class)[29]

"PE-NMe2"

### Use GOSLIN

In [143]:
R"""
suppressMessages(library('rgoslin'))
suppressMessages(library('tidyverse'));
"""

RObject{StrSxp}
 [1] "lubridate" "forcats"   "stringr"   "dplyr"     "purrr"     "readr"    
 [7] "tidyr"     "tibble"    "ggplot2"   "tidyverse" "rgoslin"   "stats"    
[13] "graphics"  "grDevices" "utils"     "datasets"  "methods"   "base"     


In [144]:
@rput dfRef;

In [145]:
R"""
# check validity
dfRef$Valid <- suppressWarnings(sapply(dfRef$StandardizedName, isValidLipidName))
if (sum(dfRef$Valid) == dim(dfRef)[1]) {
    cat("All valid.")
} else {
    print("Check invalid names.")
}
""";

All valid.

In [146]:
dfRef.Total_C = zeros(Int, size(dfRef,1));
dfRef.Total_DB = zeros(Int, size(dfRef,1));
dfRef.Class = repeat(["NA"], size(dfRef,1));

In [147]:
for i in 1:size(dfRef, 1)
    @rput i;
    R"""
    #rsltGoslin <- as_tibble(parseLipidNames(dfRef$StandardizedName[i]))[, c("Original Name", "Total C", "Total DB", "Lipid Maps Main Class")];
    rsltGoslin <- as_tibble(parseLipidNames(dfRef$StandardizedName[i]))[, c("Original.Name", "Total.C", "Total.DB", "Lipid.Maps.Main.Class")];
    """
    @rget rsltGoslin
    # dfRef.Total_C[i] = parse(Int, rsltGoslin."Total C"[1])
    # dfRef.Total_DB[i] = parse(Int, rsltGoslin."Total DB"[1])
    # dfRef.Class[i] = rsltGoslin."Lipid Maps Main Class"[1]
        
    dfRef.Total_C[i] = rsltGoslin."Total_C"[1]
    dfRef.Total_DB[i] = rsltGoslin."Total_DB"[1]
    dfRef.Class[i] = rsltGoslin."Lipid_Maps_Main_Class"[1]
end

In [148]:
names(dfRef)

22-element Vector{String}:
 "Metabolite"
 "MetaboliteID"
 "StandardizedName"
 "Oxidized"
 "OH"
 "O"
 "O₂"
 "O₃"
 "O₄"
 "Plasmanyl"
 "Plasmalogen"
 "CHO"
 "Ke"
 "exactmass"
 "formula"
 "main_class"
 "refmet_name"
 "sub_class"
 "super_class"
 "Total_C"
 "Total_DB"
 "Class"

#### Save metabolites reference dataset:

In [149]:
fileMetaboRef = joinpath(@__DIR__,"..","..","data","processed","refMeta.csv");
dfRef |> CSV.write(fileMetaboRef);

### Sub class dictionary

In [150]:
fileClinicalDict = joinpath(@__DIR__,"..","..","data","processed", "SubClassDictionary.csv");
open(fileClinicalDict,"w") do io
   println(io,
        "SubClass,Name\n",
        "Cer,Ceramides\n",
        "Chol. esters,Cholesteryl esters\n",
        "DAG,Diglycerides\n",
        "LPC,Lysophosphatidylcholines\n",
        "LPE,Lysocephalins\n",
        "PC,Phosphatidylcholines\n",
        "PE,Phosphatidylethanolamines\n" ,
        "PI,Phosphatidylinositols\n",
        "PS,Phosphatidylserines\n",
        "SM,Sphingomyelins\n",
        "TAG,Triglycerides\n"
    )
end

## Extract Metabolites dataset 

In [151]:
dfMetabo = fetch_data(ST);

In [152]:
# rename sample ID with suffix
vHeader = names(dfMetabo);
vHeader[2:end] .= "ID_".*vHeader[2:end];
rename!(dfMetabo, Symbol.(vHeader));

In [153]:
first(dfMetabo, 5)

5×52 DataFrame
 Row │ Metabolite  ID_8358      ID_8363      ID_8370      ID_8371      ID_8373 ⋯
     │ String      String       String       String       String       String  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ CE(18:1)    1005.004533  656.2196475  442.532242   835.7863174  694.993 ⋯
   2 │ CE(18:2)    120.5422615  81.57473155  59.37249758  95.26536816  111.262
   3 │ CE(18:3)    207.5760181  103.0388756  91.39644092  147.2090585  134.357
   4 │ CE(18:4)    185.1900835  114.8704705  102.3479244  214.2161794  105.070
   5 │ CE(20:1)    27.12701689  2.961702936  4.237597992  31.33287865  7.63711 ⋯
                                                              47 columns omitted

Replace `Metabolite` name information with `MetaboliteID` values:

In [154]:
dfMetaboAll = leftjoin(select(dfRefOriginal, [:Metabolite, :MetaboliteID]), dfMetabo, on = [:Metabolite]);
select!(dfMetaboAll, Not([:Metabolite]));

Select the samples that only present in the filtered clinical dataset, `dfIndividuals`:   

In [155]:
select!(dfMetaboAll, vcat([:MetaboliteID], Symbol.(dfIndividuals.SampleID)));
size(dfMetaboAll)

(590, 45)

#### Save metabolites levels dataset:

In [156]:
fileMetabo = joinpath(@__DIR__,"..","..","data","processed","Metabo.csv");
dfMetaboAll = permutedims(dfMetaboAll, 1, :SampleID);
dfMetaboAll |> CSV.write(fileMetabo);

## References

[1] Koelmel, J. P., Ulmer, C. Z., Fogelson, S., Jones, C. M., Botha, H., Bangma, J. T., Guillette, T. C., Luus-Powell, W. J., Sara, J. R., Smit, W. J., Albert, K., Miller, H. A., Guillette, M. P., Olsen, B. C., Cochran, J. A., Garrett, T. J., Yost, R. A., & Bowden, J. A. (2019). Lipidomics for wildlife disease etiology and biomarker discovery: a case study of pansteatitis outbreak in South Africa. Metabolomics : Official journal of the Metabolomic Society, 15(3), 38. https://doi.org/10.1007/s11306-019-1490-9    

[2] Kato, S., Shimizu, N., Hanzawa, Y., Otoki, Y., Ito, J., Kimura, F., Takekoshi, S., Sakaino, M., Sano, T., Eitsuka, T., Miyazawa, T., & Nakagawa, K. (2018). Determination of triacylglycerol oxidation mechanisms in canola oil using liquid chromatography-tandem mass spectrometry. NPJ science of food, 2, 1. https://doi.org/10.1038/s41538-017-0009-x    

[3] Koelmel, J. P., Ulmer, C. Z., Jones, C. M., Yost, R. A., & Bowden, J. A. (2017). Common cases of improper lipid annotation using high-resolution tandem mass spectrometry data and corresponding limitations in biological interpretation. Biochimica et biophysica acta. Molecular and cell biology of lipids, 1862(8), 766–770. https://doi.org/10.1016/j.bbalip.2017.02.016    

[4] Riewe, D., Wiebach, J., & Altmann, T. (2017). Structure Annotation and Quantification of Wheat Seed Oxidized Lipids by High-Resolution LC-MS/MS. Plant physiology, 175(2), 600–618. https://doi.org/10.1104/pp.17.00470    

[5] Koelmel, J. P., Jones, C. M., Ulmer, C. Z., Garrett, T. J., Yost, R. A., Schock, T. B., & Bowden, J. A. (2018). Examining heat treatment for stabilization of the lipidome. Bioanalysis, 10(5), 291–305. https://doi.org/10.4155/bio-2017-0209    

